### ISSUE TITLE
Incompatible with Cider 0.20.0

### ISSUE THREAD

**Issue by WorldsEndless** [luminus-framework/luminus-nrepl#6] opened 2019-02-17 04:20 UTC
luminus-nrepl, and hence Luminus itself, is incompatible with Cider 0.20.0. 

Steps to reproduce: 

`lein new luminus ltest`
navigate to a clj file
`cider-jack-in-clj`

error: 

> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Exception in thread "main" Syntax error compiling var at (/tmp/form-init6297655190044541236.clj:1:8733).
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7114)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6789)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6745)
> 	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3888)
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7108)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6789)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6745)
> 	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3888)
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7108)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6789)
> 	at clojure.lang.Compiler.access$300(Compiler.java:38)
> 	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6384)
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6789)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6745)
> 	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6120)
> 	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5467)
> 	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4029)
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7104)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6789)
> 	at clojure.lang.Compiler.eval(Compiler.java:7173)
> 	at clojure.lang.Compiler.eval(Compiler.java:7166)
> 	at clojure.lang.Compiler.load(Compiler.java:7635)
> 	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
> 	at clojure.main$load_script.invokeStatic(main.clj:452)
> 	at clojure.main$init_opt.invokeStatic(main.clj:454)
> 	at clojure.main$init_opt.invoke(main.clj:454)
> 	at clojure.main$initialize.invokeStatic(main.clj:485)
> 	at clojure.main$null_opt.invokeStatic(main.clj:519)
> 	at clojure.main$null_opt.invoke(main.clj:516)
> 	at clojure.main$main.invokeStatic(main.clj:598)
> 	at clojure.main$main.doInvoke(main.clj:561)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 	at clojure.lang.Var.applyTo(Var.java:705)
> 	at clojure.main.main(main.java:37)
> Caused by: java.lang.RuntimeException: Unable to resolve var: cider.nrepl/wrap-apropos in this context
> 	at clojure.lang.Util.runtimeException(Util.java:221)
> 	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:720)
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)
> 	... 34 more
> Subprocess failed

To fix: 

remove luminus-nrepl from the dependencies and from all code references. It then works without issue.

**Comment by yogthos** [comment] 2019-02-17 04:56
Thanks for the heads up, looks like it's likely caused by an old version of the nREPL dependency. I've updated to the latest and pushed a new version `0.1.6` to Clojars. Let me know if that fixes the issue.

**Comment by WorldsEndless** [comment] 2019-02-21 21:59
Afraid not. A brand new `lein new luminus lt` and trying to start cider got me this: 

> error in process sentinel: Could not start nREPL server: 2019-02-21 14:56:47,888 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider 
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Error loading cider.nrepl: Syntax error compiling at (cider/nrepl.clj:1:1).
> Exception in thread "main" Syntax error compiling var at (/tmp/form-init3131096959585651247.clj:1:9276).
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7114)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6789)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6745)
> 	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3888)
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7108)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6789)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6745)
> 	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3888)
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7108)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6789)
> 	at clojure.lang.Compiler.access$300(Compiler.java:38)
> 	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6384)
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6789)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6745)
> 	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6120)
> 	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5467)
> 	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4029)
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7104)
> 	at clojure.lang.Compiler.analyze(Compiler.java:6789)
> 	at clojure.lang.Compiler.eval(Compiler.java:7173)
> 	at clojure.lang.Compiler.eval(Compiler.java:7166)
> 	at clojure.lang.Compiler.eval(Compiler.java:7166)
> 	at clojure.lang.Compiler.load(Compiler.java:7635)
> 	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
> 	at clojure.main$load_script.invokeStatic(main.clj:452)
> 	at clojure.main$init_opt.invokeStatic(main.clj:454)
> 	at clojure.main$init_opt.invoke(main.clj:454)
> 	at clojure.main$initialize.invokeStatic(main.clj:485)
> 	at clojure.main$null_opt.invokeStatic(main.clj:519)
> 	at clojure.main$null_opt.invoke(main.clj:516)
> 	at clojure.main$main.invokeStatic(main.clj:598)
> 	at clojure.main$main.doInvoke(main.clj:561)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 	at clojure.lang.Var.applyTo(Var.java:705)
> 	at clojure.main.main(main.java:37)
> Caused by: java.lang.RuntimeException: Unable to resolve var: cider.nrepl/wrap-apropos in this context
> 	at clojure.lang.Util.runtimeException(Util.java:221)
> 	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:720)
> 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)
> 	... 35 more
> Subprocess failed

**Comment by yogthos** [comment] 2019-02-21 23:17
It looks like this might be a CIDER specific issue. I don't use Emacs myself, so I don't really know too much regarding what CIDER does unfortunately. This thread might help  https://github.com/clojure-emacs/cider-nrepl/issues/96

**Comment by skovuri41** [comment] 2019-02-28 03:25
adding the plugin to project.clj `[cider/cider-nrepl "0.21.1"]` seems to solve this issue.

**Comment by yogthos** [comment] 2019-02-28 17:04
I think that CIDER specific plugins should probably go in `~/.lein/profiles.clj` instead of the template. So, I'm going to close the issue.

**Closed as completed by yogthos** 2019-02-28 17:04 UTC

**Comment by WorldsEndless** [comment] 2019-02-28 17:07
I very much agree. I've actually started moving all repl-deps to profiles.clj, unless I were to need a public repl.
